image: python:3.10

before_script:
  - pip install -r requirements.txt
  - pip install pylint coverage

stages:
  - test

lint_and_test:
  stage: test
  script:
    - pylint *.py
    - coverage run test.py
    - coverage report